spring:
  #数据源
  datasource:
    url: jdbc:mysql://192.168.1.144:3306/spring?serverTimezone=Asia/Shanghai
    username: root
    password: Aimer
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JSP渲染Web视图
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates

  mvc:
    # put delete
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /static/**

  servlet:
    multipart:
      #设置单个文件大小
      max-file-size: 50MB
      #设置单次请求文件的总大小
      max-request-size: 50MB

# 扫描mapper.xml
mybatis:
  mapper-locations: classpath:/mapper/*.xml

# 把日志打印到控制台
logging:
  level:
   com.yr.mapper: DEBUG

server:
  port: 8081
